---
- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ cert_path }}/{{ ansible_hostname }}.crt"
    privatekey_path: "{{ cert_path }}/{{ ansible_hostname }}.pem"
    csr_path: "{{ cert_path }}/{{ ansible_hostname }}.csr"
    provider: selfsigned

- name: Copying origin_trail configuration 
  template: 
    src: "templates/origintrail.j2"
    dest: "{{ origin_trail_user }}/.origintrail_noderc"

- name: Copy docker-compose template
  template: 
    src: "templates/docker-compose.yml.j2"
    dest: "{{ origin_trail_user }}/docker-compose.yml"

- name: pulling the origin_trail node images
  shell: "docker-compose -f {{ origin_trail_user }}/docker-compose.yml pull" 

#- name: running the origin_trail node 
#  shell: "docker-compose -f {{ origin_trail_user }}/docker-compose.yml up -d"
