---
- name: Allow all access to required tcp port
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ required_ports }}"

- name: enable UFW
  ufw:
    state: enabled

- name: Set logging
  ufw:
    logging: 'on'

- name: creating certs directory
  file:
    path: "{{ cert_path }}" 
    state: directory

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ cert_path }}/{{ ansible_hostname }}.pem"
    size: "{{ key_size }}"
    type: "{{ key_type }}"
    backup: yes

- name: Generate an OpenSSL Certificate Signing Request with Subject information
  openssl_csr:
    path: "{{ cert_path }}/{{ ansible_hostname }}.csr"
    privatekey_path: "{{ cert_path }}/{{ ansible_hostname }}.pem"
    country_name: "{{ country_name }}"
    organization_name: "{{ organization_name }}"
    email_address: "{{ email_address }}"
    common_name: "{{ ansible_hostname }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ cert_path }}/{{ ansible_hostname }}.crt"
    privatekey_path: "{{ cert_path }}/{{ ansible_hostname }}.pem"
    csr_path: "{{ cert_path }}/{{ ansible_hostname }}.csr"
    provider: selfsigned

- name: Copying origin_trail configuration 
  template: 
    src: "templates/origintrail.j2"
    dest: "/{{ origin_trail_user }}/.origintrail_noderc"

- name: Copy docker-compose template
  template: 
    src: "templates/docker-compose.yml.j2"
    dest: "/{{ origin_trail_user }}/docker-compose.yml"

- name: pulling the origin_trail node images
  shell: "docker-compose pull" 

- name: running the origin_trail node 
  shell: "docker-compose up -d"
